<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Find_member</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c2b20c41-c9f7-4d79-a528-5372a63f3ed5</testSuiteGuid>
   <testCaseLink>
      <guid>6400ae20-2eae-4d93-ab1e-1f91925212ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Invite_member/Find_by_email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88a134cf-286a-4329-9a12-08f442019101</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ecef25bd-464e-448a-8ae9-34fd35cd3e97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Invite_member/Find_exist_member</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3332ca98-7216-4951-8ef1-ce4c4e00b3e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ca626a4-f5e7-4bab-b84c-7506b2fd6417</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Invite_member/Find_unexist_member</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5d9e441-c58b-4d42-a0b7-3d947aa1438c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
