<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ApiTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2384f074-0f9b-4497-b6a1-0c6bf631856c</testSuiteGuid>
   <testCaseLink>
      <guid>b42a0655-31ab-4305-a9b0-5f0a74e94b41</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC_API/Sign Up</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1566b358-768d-4aab-ab18-e7c29422ff51</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataApi/SignUp</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>1566b358-768d-4aab-ab18-e7c29422ff51</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>44833b66-347e-477d-8696-8eb7cc2ec48e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1566b358-768d-4aab-ab18-e7c29422ff51</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>fc777c4c-896c-45a6-bba9-ad6e83ea6f06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1566b358-768d-4aab-ab18-e7c29422ff51</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>cac34403-a58a-40b2-9e25-ae00241613fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63965bb4-4cbc-40e7-a1dc-e5a22356cfa4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC_API/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d71385b1-05ad-431d-8819-21b92dfa6218</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataApi/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4556db9b-3cfc-46fd-9b7b-81f2a1364442</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d273042-3003-4ab8-83d8-391b02e442a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7b1a273-c7ce-40d7-9124-2a3e0d255619</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_API/Login_SaveCookie</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55a6d4ad-62ca-40a1-8ddb-30a8017d4050</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13d1c761-4306-4d06-b725-29f3d8ce98a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1736cab-eb0e-438c-b5eb-eae9812d25e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_API/SystemLog</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>078d5cc0-da5b-4e1d-8a92-43aac8348804</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_API/Statistics</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3d3dcb80-0fa1-4d28-818f-61a4016f44f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_API/GetStatusPlugin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79c4976a-e3cd-40bc-a9c3-14247c698d11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e68acffa-25e3-4ce5-84f6-09858d7e76f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad049491-6d36-4027-92a8-b6bc30a6d3ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_API/GetUsers</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>28728467-83b0-472a-8e15-8cb6a36fece1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_API/ViewMembers</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>389386c0-ef4d-46d0-8fc6-0186e061bd7c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataApi/ViewMembers</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>389386c0-ef4d-46d0-8fc6-0186e061bd7c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ChannelID</value>
         <variableId>f21c433a-eb54-4e1e-97a6-6309cc1a2b7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0cb95685-6ccf-415e-abe4-24d706907ab3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_API/ViewChannels</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e004919d-78df-4a7a-b484-34a44402b0a7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataApi/ViewMembers</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e004919d-78df-4a7a-b484-34a44402b0a7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ChannelID</value>
         <variableId>d1488c65-cd9d-49e0-a2e3-adab39947f7b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
